from __future__ import annotations

import argparse
import json
import pathlib
import random

SAMPLES = [
    dict(
        title="Team Lead Backend",
        company_name="Т-Банк",
        company_description="Крупнейший финтех холдинг",
        company_industry="FinTech",
        location="Москва",
        work_format="hybrid",
        salary_range_from=600000,
        salary_range_to=750000,
        responsibilities="Руководство командой 5-12 человек, планирование релизов, взаимодействие с бизнесом",
        vacancy_stack="Kotlin, Java, PostgreSQL, Kafka",
        vacancy_skills=["Team management", "System design", "Fintech"],
        questions="1. В каком городе находитесь?\n2. Какие зарплатные ожидания?\n3. Какой опыт руководства командой?\n4. С какими highload-системами работали?",
    ),
    dict(
        title="Senior DevOps Engineer",
        company_name="OntheTop Agency",
        company_description="Аутсорс-команда рекрутеров и девопсов",
        company_industry="Software",
        location="Санкт-Петербург",
        work_format="remote",
        salary_range_from=320000,
        salary_range_to=380000,
        responsibilities="CI/CD, observability, оптимизация инфраструктуры клиентов",
        vacancy_stack="AWS, Kubernetes, Terraform",
        vacancy_skills=["Helm", "Prometheus", "Python scripting"],
        questions="1. Где проживаете?\n2. Комфортный уровень дохода?\n3. Есть ли опыт с AWS EKS?\n4. Как строили мониторинг?",
    ),
    dict(
        title="Senior Golang Developer",
        company_name="HR Pro Lab",
        company_description="Разрабатываем инструменты для рекрутинга",
        company_industry="HRTech",
        location="Казань",
        work_format="hybrid",
        salary_range_from=280000,
        salary_range_to=350000,
        responsibilities="Разработка микросервисов на Go, интеграции с Telegram и Slack",
        vacancy_stack="Go, gRPC, PostgreSQL, Redis",
        vacancy_skills=["Go", "GRPC", "PostgreSQL", "Docker"],
        questions="1. Текущая локация?\n2. ЗП ожидания (net)?\n3. Опыт с высоконагруженными сервисами?\n4. Стек любимых инструментов?",
    ),
    dict(
        title="Product Manager (B2C)",
        company_name="Aurika Digital",
        company_description="Маркетплейс HR-услуг",
        company_industry="Marketplace",
        location="Екатеринбург",
        work_format="remote",
        salary_range_from=220000,
        salary_range_to=260000,
        responsibilities="Запуск воронок привлечения, CustDev, аналитика метрик",
        vacancy_stack="Product analytics, SQL, Notion",
        vacancy_skills=["Hypothesis testing", "A/B", "Customer interviews"],
        questions="1. Где живёте?\n2. Current/desired грейд и доход?\n3. Опыт продуктовой разработки?\n4. Какие метрики вели?",
    ),
    dict(
        title="QA Automation Engineer",
        company_name="Sabina HR",
        company_description="Продукт для автоматизации подбора",
        company_industry="Software",
        location="Минск",
        work_format="remote",
        salary_range_from=180000,
        salary_range_to=230000,
        responsibilities="Покрытие UI/API тестами, поддержка пайплайнов, контроль качества релизов",
        vacancy_stack="Python, Playwright, Jenkins",
        vacancy_skills=["Python", "Playwright", "REST", "GitLab CI"],
        questions="1. Где находитесь?\n2. Комфортный рейт?\n3. Есть ли опыт с Playwright?\n4. Как выстраивали тестовую стратегию?",
    ),
    dict(
        title="Data Scientist NLP",
        company_name="Marina HR IT",
        company_description="Развиваем поисковые модели для поддержки рекрутинга",
        company_industry="AI",
        location="Новосибирск",
        work_format="remote",
        salary_range_from=280000,
        salary_range_to=330000,
        responsibilities="Разработка LLM-пайплайнов, аннотирование данных, A/B гипотез",
        vacancy_stack="Python, PyTorch, Transformers",
        vacancy_skills=["LLM fine-tuning", "MLOps", "Vector DB"],
        questions="1. Ваша локация?\n2. Зарплатные ожидания?\n3. Есть ли опыт с GPT/LLM?\n4. Проекты по NLP?",
    ),
    dict(
        title="Senior Frontend Engineer",
        company_name="AlexiosHR",
        company_description="Инхаус-платформа для рекрутеров",
        company_industry="Software",
        location="Москва",
        work_format="hybrid",
        salary_range_from=260000,
        salary_range_to=320000,
        responsibilities="Развитие кабинета рекрутера, оптимизация производительности, дизайн-система",
        vacancy_stack="React, TypeScript, Next.js",
        vacancy_skills=["React", "Next.js", "GraphQL"],
        questions="1. Город проживания?\n2. Какой уровень дохода ищете?\n3. Опыт с SSR?\n4. Примеры UI проектов?",
    ),
    dict(
        title="Python Backend Developer",
        company_name="IT Anna",
        company_description="Аутсорс-команда для сервисов доставки",
        company_industry="Logistics",
        location="Казахстан / Астана",
        work_format="remote",
        salary_range_from=200000,
        salary_range_to=260000,
        responsibilities="Поддержка API курьерских сервисов, интеграции с CRM",
        vacancy_stack="Python, FastAPI, PostgreSQL",
        vacancy_skills=["FastAPI", "SQL", "Docker"],
        questions="1. Текущая локация?\n2. Ближайшие ожидания по ставке?\n3. Есть ли опыт с FastAPI?\n4. Как строили интеграции?",
    ),
    dict(
        title="Lead Mobile Engineer",
        company_name="OntheTop Studio",
        company_description="Собираем мобильные команды под заказ",
        company_industry="Mobile",
        location="Сочи",
        work_format="remote",
        salary_range_from=300000,
        salary_range_to=360000,
        responsibilities="Управление iOS/Android командой, аудит приложений, архитектура",
        vacancy_stack="Swift, Kotlin, Firebase",
        vacancy_skills=["SwiftUI", "Kotlin Multiplatform", "App Store release"],
        questions="1. Где проживаете?\n2. Уровень компенсации?\n3. Опыт руководства мобильной командой?\n4. Какие приложения запускали?",
    ),
    dict(
        title="System Analyst",
        company_name="Victory IT Recruiting",
        company_description="Продукты для телекома",
        company_industry="Telecom",
        location="Ростов-на-Дону",
        work_format="hybrid",
        salary_range_from=180000,
        salary_range_to=210000,
        responsibilities="Сбор требований, BPMN схемы, постановка задач разработчикам",
        vacancy_stack="Confluence, BPMN, SQL",
        vacancy_skills=["BPMN", "UML", "SQL"],
        questions="1. Город проживания?\n2. Желаемая компенсация?\n3. Опыт с телеком-проектами?\n4. Примеры интеграций?",
    ),
    dict(
        title="Security Engineer",
        company_name="QuickMike",
        company_description="Инфосек-консалтинг для финтеха",
        company_industry="Cybersecurity",
        location="Москва",
        work_format="office",
        salary_range_from=350000,
        salary_range_to=420000,
        responsibilities="Аудит инфраструктуры, SOC, реагирование на инциденты",
        vacancy_stack="ELK, SIEM, Python",
        vacancy_skills=["SOC", "Threat hunting", "Cloud security"],
        questions="1. Доступен ли офис в Москве?\n2. Зарплатные ожидания?\n3. Опыт с SOC/SIEM?\n4. Есть ли сертификаты?",
    ),
    dict(
        title="BI Developer",
        company_name="VestaPro IT",
        company_description="Внутренние аналитические отчёты",
        company_industry="Retail",
        location="Нижний Новгород",
        work_format="hybrid",
        salary_range_from=170000,
        salary_range_to=210000,
        responsibilities="Подготовка витрин, dwh, отчётность для бизнеса",
        vacancy_stack="Power BI, SQL, Airflow",
        vacancy_skills=["DWH", "Power BI", "ETL"],
        questions="1. Где находитесь?\n2. На какую компенсацию ориентируетесь?\n3. Опыт построения витрин?\n4. Какие BI инструменты использовали?",
    ),
    dict(
        title="Lead UX/UI Designer",
        company_name="Roza HR",
        company_description="Стартап по автоматизации найма",
        company_industry="SaaS",
        location="Санкт-Петербург",
        work_format="remote",
        salary_range_from=210000,
        salary_range_to=260000,
        responsibilities="UX-исследования, дизайн-система, поддержка web/mobile",
        vacancy_stack="Figma, FigJam, JTBD",
        vacancy_skills=["Figma", "JTBD", "Design tokens"],
        questions="1. Локация?\n2. Уровень дохода?\n3. Есть ли опыт с b2b SaaS?\n4. С какими дизайн-системами работали?",
    ),
    dict(
        title="Business Development Manager",
        company_name="Sabina HR Pro",
        company_description="Агентство, которое продаёт рекрутинговые услуги",
        company_industry="HR services",
        location="Москва",
        work_format="hybrid",
        salary_range_from=200000,
        salary_range_to=240000,
        responsibilities="Холодные/тёплые продажи, поддержка клиентов, участие в тендерах",
        vacancy_stack="CRM, Pitch decks",
        vacancy_skills=["Negotiation", "B2B sales", "CRM"],
        questions="1. Где вы находитесь?\n2. Какие финансовые ожидания?\n3. Есть ли опыт продаж HR-услуг?\n4. Готовы ли к командировкам?",
    ),
    dict(
        title="Scala Developer",
        company_name="Natali Tech",
        company_description="Разрабатываем антифрод системы",
        company_industry="FinTech",
        location="Москва",
        work_format="office",
        salary_range_from=300000,
        salary_range_to=360000,
        responsibilities="Поддержка антифрод платформы, разработка потоковой обработки",
        vacancy_stack="Scala, Kafka, Cassandra",
        vacancy_skills=["Scala", "Kafka Streams", "Microservices"],
        questions="1. Город проживания?\n2. Уровень компенсации?\n3. Опыт с Scala?\n4. Работали ли с antifraud продуктами?",
    ),
    dict(
        title="Full-stack Engineer",
        company_name="Mary IT",
        company_description="Инхаус команда, развивающая маркетплейс",
        company_industry="E-commerce",
        location="Москва",
        work_format="hybrid",
        salary_range_from=230000,
        salary_range_to=290000,
        responsibilities="Развитие личного кабинета, React + Node, интеграция платежей",
        vacancy_stack="React, Node.js, PostgreSQL",
        vacancy_skills=["React", "Node.js", "SQL"],
        questions="1. Локация?\n2. Финансовые ожидания?\n3. Опыт с full-stack?\n4. Какие фичи запускали?",
    ),
    dict(
        title="Project Manager (AI)",
        company_name="Marian Vision",
        company_description="Запускаем проекты с ML/AI для enterprise",
        company_industry="Consulting",
        location="Новосибирск",
        work_format="remote",
        salary_range_from=240000,
        salary_range_to=280000,
        responsibilities="Согласование roadmap, контроль спринтов, работа с заказчиками",
        vacancy_stack="Agile, Jira, Notion",
        vacancy_skills=["Scrum", "Kanban", "Stakeholder management"],
        questions="1. Где находитесь?\n2. Какая ставка интересна?\n3. Опыт ведения AI проектов?\n4. Какое ПО использовали?",
    ),
    dict(
        title="Data Engineer",
        company_name="ProHR Alena",
        company_description="Продукты аналитики HR-процессов",
        company_industry="Analytics",
        location="Самара",
        work_format="hybrid",
        salary_range_from=220000,
        salary_range_to=260000,
        responsibilities="ETL пайплайны, оптимизация хранилища, интеграции с ATS",
        vacancy_stack="Python, Airflow, ClickHouse",
        vacancy_skills=["Airflow", "ClickHouse", "ETL"],
        questions="1. Локация?\n2. Доходная планка?\n3. Опыт с ClickHouse?\n4. Какие ETL строили?",
    ),
    dict(
        title="HR Tech Support Lead",
        company_name="Sveta SuperHR",
        company_description="Поддержка пользователей HR-платформы",
        company_industry="Support",
        location="Казань",
        work_format="remote",
        salary_range_from=150000,
        salary_range_to=190000,
        responsibilities="Организация L1/L2 поддержки, KPI, автоматизация FAQ",
        vacancy_stack="Zendesk, Confluence",
        vacancy_skills=["Support management", "Automation", "Knowledge base"],
        questions="1. Где проживаете?\n2. Уровень дохода?\n3. Опыт управления поддержкой?\n4. Какие инструменты использовали?",
    ),
    dict(
        title="Site Reliability Engineer",
        company_name="Telecom Aurora",
        company_description="Платформа голосовых ассистентов",
        company_industry="Telecom",
        location="Краснодар",
        work_format="remote",
        salary_range_from=310000,
        salary_range_to=370000,
        responsibilities="SLO/SLA, инциденты, масштабирование сервисов",
        vacancy_stack="GCP, Kubernetes, Go",
        vacancy_skills=["SRE", "Go", "Monitoring"],
        questions="1. Текущий город?\n2. Компенсация?\n3. Опыт SRE?\n4. Как настраивали SLO?",
    ),
    dict(
        title="Marketing Analyst",
        company_name="HR Vector",
        company_description="Маркетинг рекрутинговых продуктов",
        company_industry="Marketing",
        location="Москва",
        work_format="hybrid",
        salary_range_from=160000,
        salary_range_to=200000,
        responsibilities="Аналитика каналов, дашборды, прогноз воронки",
        vacancy_stack="Looker, GA4, SQL",
        vacancy_skills=["SQL", "GA4", "Retention analysis"],
        questions="1. Где находитесь?\n2. Готовый уровень дохода?\n3. Опыт построения маркетинговых отчётов?\n4. Работали с GA4?",
    ),
    dict(
        title="IT Project Coordinator",
        company_name="Aurika SB",
        company_description="Интегратор корпоративных решений",
        company_industry="Enterprise IT",
        location="Москва",
        work_format="office",
        salary_range_from=180000,
        salary_range_to=210000,
        responsibilities="Координация подрядчиков, контроль сроков, отчётность",
        vacancy_stack="Jira, MS Project",
        vacancy_skills=["Project tracking", "Risk management", "Communication"],
        questions="1. Город проживания?\n2. Ожидаемая ставка?\n3. Опыт сопровождения интеграционных проектов?\n4. Готовы к офису?",
    ),
]

RECRUITERS = [
    "Лиза",
    "Барбара",
    "Света",
    "Марина",
    "Сабина",
    "Аурика",
    "Виктория",
    "Марина HR",
    "Веста",
    "Алексей HR",
]

CANDIDATES = [
    "Дмитрий",
    "Алексей",
    "Мария",
    "Илья",
    "Наталья",
    "Антон",
    "Евгения",
    "Павел",
    "Татьяна",
    "Сергей",
]


def make_cdm(
    recruiter_name: str | None = None,
    candidate_name: str | None = None,
) -> dict:
    vacancy = random.choice(SAMPLES).copy()
    recruiter = recruiter_name or random.choice(RECRUITERS)
    candidate = candidate_name or random.choice(CANDIDATES)
    return {
        "vacancy": vacancy,
        "candidate": {
            "recruiter_name": recruiter,
            "candidate_name": candidate,
            "candidate_contacts": [],
            "candidate_job_list": [],
            "candidate_skills": [],
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out_dir", default="tests/fixtures/cdm")
    parser.add_argument("--n", type=int, default=3)
    args = parser.parse_args()

    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for idx in range(args.n):
        cdm = make_cdm()
        path = out_dir / f"cdm_{idx + 1:02d}.json"
        path.write_text(json.dumps(cdm, ensure_ascii=False, indent=2), encoding="utf-8")
        print("Wrote", path)


if __name__ == "__main__":
    main()
